"""Update KnowledgeBaseTopic model

Revision ID: 359875c4a81b
Revises: 06ef63bdb95b
Create Date: 2024-08-19 22:01:50.039080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359875c4a81b'
down_revision = '06ef63bdb95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_topic', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_knowledge_base_topic_name', ['name'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_knowledge_base_topic_name', type_='unique')

    # ### end Alembic commands ###
