"""Add IntegrationSetting model

Revision ID: 503967b77ec5
Revises: 79704880e8e5
Create Date: 2024-08-14 11:14:21.383723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503967b77ec5'
down_revision = '79704880e8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integration_setting')
    # ### end Alembic commands ###
