"""Add deleted column to Ticket model

Revision ID: 79704880e8e5
Revises: c40448a7e3c4
Create Date: 2024-08-12 15:06:29.357507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79704880e8e5'
down_revision = 'c40448a7e3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
