"""empty message

Revision ID: f0ce5353953a
Revises: 503967b77ec5
Create Date: 2024-08-14 15:03:44.521833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ce5353953a'
down_revision = '503967b77ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('api_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('project_key', sa.String(length=20), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jira_issue_key', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('jira_issue_key')

    with op.batch_alter_table('integration_setting', schema=None) as batch_op:
        batch_op.drop_column('project_key')
        batch_op.drop_column('api_token')
        batch_op.drop_column('username')
        batch_op.drop_column('api_url')

    # ### end Alembic commands ###
